package de.uni.bielefeld.sc.hterhors.psink.obie.projects.soccerplayer.ontology.interfaces;

import de.uni.bielefeld.sc.hterhors.psink.obie.core.ontology.annotations.AssignableSubInterfaces;
import de.uni.bielefeld.sc.hterhors.psink.obie.core.ontology.annotations.ImplementationClass;
import de.uni.bielefeld.sc.hterhors.psink.obie.projects.soccerplayer.ontology.classes.Team;

/**
 *
 * @author hterhors
 *
 *
 *         Sep 6, 2018
 */

@AssignableSubInterfaces(get = { IWrexhamFC.class, ICelticBoysClub.class, IFcUtrecht.class, ILDAlajuelense.class,
		IPofcBotevVratsa.class, IWiganAthleticFC.class, ISfaxRailwaysSports.class, ICameroonNationalFootballTeam.class,
		IAugustFootballClub.class, ISCBeiraMar.class, ICircoloSportivoItaliano.class, IOngcFC.class,
		IGrenobleFoot38.class, INkanaFC.class, IKDiegemSport.class, IQatarSc.class,
		IAmericanSamoaNationalAssociationFootballTeam.class, ISheffieldWednesdayFC.class, IFortLauderdaleStrikers.class,
		IExeterCityFC.class, IMaltaNationalFootballTeam.class, IHfcHaarlem.class, IMumbaiTigersFC.class,
		IBedminsterFC.class, ISouthendUnitedFC.class, IACMonzaBrianza1912.class, ITauroFC.class, IBraintreeTownFC.class,
		ITokushimaVortis.class, IBoNessUnitedFC.class, IFcDynamoMoscow.class, IBradfordParkAvenueAFC.class,
		ISouthKoreaNationalUnder17FootballTeam.class, IFcVolynLutsk.class, IPersijaJakarta.class, IBarnsleyFC.class,
		IEnglandNationalFootballTeam.class, IAlgeriaNationalFootballTeam.class, IHamborn07.class,
		IScTavriyaSimferopol.class, IHednesfordTownFC.class, IChesterfieldFC.class, IRomaniaNationalFootballTeam.class,
		IMillwallFC.class, IFcDenBosch.class, IRosarioCentral.class, ILeytonOrientFC.class, ICowdenbeathFC.class,
		ISliemaWanderersFC.class, ISunHeiSc.class, IGuiseleyAFC.class, IRhylFC.class, IOceanBoysFC.class,
		IParefSouthridgeSchool.class, IVeteransBviFootball.class, ISantaCruzFutebolClube.class, IAsMonacoFc.class,
		IGuineaNationalFootballTeam.class, ICercleBruggeKSV.class, IPohangSteelers.class, IStokeCityFC.class,
		IBritishVirginIslandsNationalFootballTeam.class, IClydebankFC.class, IWillemIiFootballClub.class,
		IAlQuwaAlJawiya.class, IBathCityFC.class, IIfElfsborg.class, IFcMetz.class, ITranmereRoversFC.class,
		IPfcChernoMoreVarna.class, IFredrikstadFk.class, IZamalekSc.class, IThackleyFC.class, ISloughTownFC.class,
		INewcastleUnitedFC.class, IFcSheriffTiraspol.class, IClubNacionalDeFootball.class, ISheffieldUnitedFC.class,
		IEastGermanyNationalFootballTeam.class, ITeignmouthFC.class, IQatarNationalUnder23FootballTeam.class,
		IMontroseFC.class, ISouthAfricaNationalFootballTeam.class, IHeiderSv.class, ITottenhamHotspurFC.class,
		ISingaporeNationalFootballTeam.class, ICFOsBelenenses.class, IAACEagles.class, IUslDunkerque.class,
		IClubLitoral.class, ISouthChinaAa.class, IVitesse.class, IClaphamRoversFC.class,
		IDenmarkNationalFootballTeam.class, IAlumniAthleticClub.class, IMsvDuisburg.class, IPowerDynamosFC.class,
		IFulhamFC.class, ICoventryCityFC.class, IFeyenoord.class, IGrenadaNationalFootballTeam.class,
		IStJohnstoneFC.class, I_1FcFemina.class, INorwayNationalFootballTeam.class, INorwichCityFC.class,
		IPfcKaliakraKavarna.class, IPakistan.class, ITheStrongest.class, IBurnleyFC.class, IDempoSC.class,
		IUruguayNationalFootballTeam.class, ISouthernSamity.class, IWestBromwichAlbionFC.class, IChelmsfordCityFC.class,
		IDoverAthleticFC.class, ICzechoslovakiaNationalFootballTeam.class, IPaokFC.class, IPsmMakassar.class,
		IClubTijuana.class, IArkaGdynia.class, ITechnoAryanFC.class, IBorussiaDortmund.class, IFcVolendam.class,
		ICasualsFC.class, IPelsallVillaFC.class, IIsraelNationalUnder21FootballTeam.class, IDalianAerbinFC.class,
		ICrusadersFC.class, IJuventusFC.class, IEgyptNationalFootballTeam.class, IFcGirondinsDeBordeaux.class,
		IOldForestersFC.class, IQatarNationalFootballTeam.class, IPuneFC.class, IChurchillBrothersSC.class,
		IBotafogoDeFutebolERegatas.class, IClubUniversidadDeChile.class, IHarwichParkestonFC.class,
		IFranceWomenSNationalFootballTeam.class, IVvvVenlo.class, IXerezCd.class, IDalianShideFC.class,
		IFcAkademiyaTolyatti.class, ITeamSoccerooFC.class, IFalkenbergsFf.class, ITorquayUnitedFC.class,
		ISunderlandAFC.class, IChelseaFC.class, ISwanseaCityAFC.class, ILiverpoolFC.class,
		ICostaRicaNationalFootballTeam.class, IKBeerschotVAC.class, ICoritibaFootBallClub.class, IClubAfricain.class,
		IOgcNice.class, IMexicoWomenSNationalFootballTeam.class, IDarlingtonFC.class, IGuangdongSunrayCaveFC.class,
		IAtlantaChiefs.class, IWiganBoroughFC.class, IBelgiumNationalFootballTeam.class, IKBocholterVV.class,
		IScBastia.class, IRcKouba.class, INorthKoreaNationalFootballTeam.class, ICrookTownAFC.class,
		IGrimsbyTownFC.class, IBuxtonFC.class, IDefensoresDeBelgrano.class, IRDaringClubMolenbeek.class,
		IAFCBournemouth.class, I_1SimmeringerSc.class, ISouthamptonFC.class, IPacificLutheranUniversity.class,
		IMamelodiSundownsFC.class, IGuizhouRenheFC.class, IBahrainNationalFootballTeam.class, IHaringeyBoroughFC.class,
		IBarbadosNationalFootballTeam.class, ILivingstonFC.class, IToulouseFc.class, IEvertonFC.class,
		IPeruNationalFootballTeam.class, IMiddlesbroughFC.class, IFcMidtjylland.class, IFcAk.class,
		IAustriaNationalFootballTeam.class, IDundeeUnitedFC.class, IPortsAuthorityFC.class, ICDTrofense.class,
		IIfkEskilstuna.class, ITruroCityFC.class, IAlAnsarSc.class, IPyongyangCitySportsClub.class,
		INetherlandsNationalFootballTeam.class, IGooleAFC.class, IClubSocialYDeportivoFlandria.class,
		IZambiaNationalFootballTeam.class, IColchesterUnitedFC.class, IVancouverRoyals.class, IAikFotboll.class,
		IArmthorpeWelfareFC.class, IMaccabiTelAvivFC.class, IBlackpoolFC.class, IEgersundsIk.class, IPooleTownFC.class,
		ISanMarinoNationalFootballTeam.class, ISalgaocarFC.class, IArnettGardensFC.class, IUnitedSikkimFC.class,
		IKorinthosFC.class, IVagonulArad.class, IVsiTampaBayFc.class, IDominicaNationalFootballTeam.class,
		IIkSleipner.class, IPersiramRajaAmpat.class, IDeportivoTolucaFC.class, IRajaCasablanca.class, IFCEtar.class,
		IFCPorto.class, IMarlowFC.class, IFcPuumaTallinn.class, IGloucesterCityAFC.class, IPaykanFC.class,
		IMasFez.class, IPullmanFC.class, IChicagoSting.class, IAsDouanesDakar.class, IMumbaiFC.class,
		IDagenhamRedbridgeFC.class, IMerthyrTownFC.class, IGreenockMortonFC.class,
		ICookIslandsNationalFootballTeam.class, IBayelsaUnitedFC.class, IGefleIf.class, IWienerSportClub.class,
		INottinghamForestFC.class, IHapoelIroniKiryatShmonaFC.class, IFcAarau.class, IDerbyCountyFC.class,
		IBirminghamCityFC.class, IShrewsburyTownFC.class, IJsKabylie.class, IKhaitanSportingClub.class,
		IHaitiNationalFootballTeam.class, IAlSalmiyaSc.class, IBangorCityFC.class, IAlianzaLima.class, IBlythFC.class,
		IVeriaFC.class, INasarawaUnitedFC.class, IDeportivoMongomo.class, IMontpellierHsc.class, IFcKharkiv.class,
		IQadsiaSc.class, IBradfordCityAFC.class, IEstoniaNationalFootballTeam.class, IIraqNationalFootballTeam.class,
		ISkKladno.class, IFcGueugnon.class, IUsOuakam.class, ILevadiakosFC.class, ILebanonNationalFootballTeam.class,
		ISportingClubeDePortugal.class, IManchesterUnitedFC.class, ISaudiArabiaNationalFootballTeam.class,
		IIpswichTownFC.class, IADBaucau.class, IEnosisNeonParalimniFc.class, IIndiaNationalUnder19FootballTeam.class,
		IMvvMaastricht.class, IEastFifeFC.class, IFcTwente.class, IRCharleroiSC.class, IHamiltonAcademicalFC.class,
		IWillingtonAFC.class, ITamworthFC.class, IQueenSParkFC.class, IHondurasNationalFootballTeam.class,
		IPfcLevskiSofia.class, IWisbechTownFC.class, IMoorGreenFC.class, IFcDordrecht.class, IArsenalFC.class,
		ISpartaRotterdam.class, IEquatorialGuineaNationalFootballTeam.class, IMansfieldTownFC.class,
		IShillongLajongFC.class, IBristolRoversFC.class, ICreditonUnitedAFC.class, IYorkCityFC.class,
		IFreemantleFC.class, ISandvikensIf.class, IFcDesnaChernihiv.class, ISierraLeoneNationalFootballTeam.class,
		IIsHalmia.class, IBrightonHoveAlbionFC.class, IKSintTruidenseVV.class, IAberdeenFC.class, IUnionDouala.class,
		IPortValeFC.class, IAnkaraDemirspor.class, IJamaicaNationalFootballTeam.class, IAcHorsens.class,
		IIttihadFc.class, IKikwanchaPyongyang.class, ICDMotagua.class, IHalifaxTownAFC.class, IRealGarcilaso.class,
		IAkademiskBoldklub.class, IKigwanchaSportsClub.class, IFcGroningen.class, IWaBoufarik.class, IVikingFk.class,
		IPecZwolle.class, IStranraerFC.class, IBoldklubbenFrem.class, IAlArabiScQatar.class, IOudHeverleeLeuven.class,
		IAjaxCapeTownFC.class, IFleetwoodTownFC.class, IDundeeFC.class, IAstonVillaFC.class, ICalcioPadova.class,
		IPfcCskaSofia.class, IMiltonKeynesDonsFC.class, IRangdajiedUnitedFC.class, ITunisiaNationalFootballTeam.class,
		IAdDiliOeste.class, IFranceNationalFootballTeam.class, IWydadCasablanca.class,
		INorthernIrelandNationalUnder21FootballTeam.class, IFkAustriaWien.class, IDeportivoSaprissa.class, IFcOss.class,
		IEnglandNationalUnder17FootballTeam.class, IHungaryNationalFootballTeam.class, IBasingstokeTownFC.class,
		IBulgariaNationalFootballTeam.class, ILincolnCityFC.class, IArgentinaNationalFootballTeam.class,
		ISouthportFC.class, IFkHaugesund.class, IAsfaYennenga.class, IGermanyNationalFootballTeam.class,
		IHeartlandFC.class, IPfcBotevPlovdiv.class, ISportingCristal.class, IPfcSpartakPleven.class,
		IDunfermlineAthleticFC.class, IRbcRoosendaal.class, ICentroDeFutebolZicoSociedadeEsportiva.class,
		IThandaRoyalZuluFC.class, IGraysAthleticFC.class, IFirstViennaFc.class, IHarlandAndWolff.class,
		IPfcLokomotivSofia.class, ILuxembourgNationalFootballTeam.class, IJomoCosmosFC.class, IBristolCityFC.class,
		IShenzhenRubyFC.class, ISwedenNationalFootballTeam.class, IDonBoscoFc.class, ISeoulArmyClub.class,
		IBostonUnitedFC.class, IBoltonWanderersFC.class, IUsBoulogne.class, IIranNationalUnder20FootballTeam.class,
		IFrickleyAthleticFC.class, IKazmaSportingClub.class, IMoroccoNationalFootballTeam.class,
		INigeriaNationalFootballTeam.class, IChesterCityFC.class, IPortugalNationalFootballTeam.class,
		IMexicoNationalFootballTeam.class, ICarlisleUnitedFC.class, INotreDameSc.class, IClydeFC.class,
		IClubNacional.class, IVancouverWhitecapsFc.class, IStockportCountyFC.class, IPfcSlaviaSofia.class,
		IClubLibertad.class, IGais.class, IOwlertonFC.class, IUnitedStatesMenSNationalSoccerTeam.class, IRcLens.class,
		IAsNancy.class, IOlympiqueDeMarseille.class, ISarpsborg08Ff.class, I_1FcMagdeburg.class, IPuaikuraFc.class,
		IDanubioFC.class, INewportCountyAFC.class, IWalesNationalFootballTeam.class, IMohunBaganAC.class,
		IMontpellierHscLadies.class, IScotlandNationalFootballTeam.class, ISogndalFotball.class,
		ISouthKoreaNationalFootballTeam.class, IScTelstar.class, IOmanNationalFootballTeam.class, IAtalantaBC.class,
		IHangzhouGreentownFC.class, IGombakUnitedFc.class, ITimorLesteNationalFootballTeam.class, ILouthUnitedFC.class,
		IWolverhamptonWanderersFC.class, ICharlestonBattery.class, ITulsaGoldenHurricaneMenSSoccer.class,
		IWeymouthFC.class, IWimbledonFC.class, IFarRabat.class, IKuwaitNationalFootballTeam.class,
		IArisThessalonikiFCWomen.class, IHuddersfieldTownFC.class, IJuanAurich.class,
		IHungaryWomenSNationalFootballTeam.class, IHartlepoolUnitedFC.class, IIslandersFc.class,
		IGreeceWomenSNationalFootballTeam.class, ILandskronaBois.class, IConsettAFC.class, INacBreda.class,
		IDjiboutiNationalFootballTeam.class, IArbroathFC.class, ICorinthianFC.class, IKuwaitSc.class,
		IBarkingsideFC.class, IBoliviaNationalFootballTeam.class, IAjAuxerre.class, ILutonTownFC.class,
		IIndonesiaNationalFootballTeam.class, IAnchorQueensParkRangersFc.class, IAccraHeartsOfOakSc.class,
		IDeportivoCoopsol.class, IMacclesfieldTownFC.class, IAlArabiScKuwait.class, ISkBrann.class,
		IParaguayNationalFootballTeam.class, IBlackburnRoversFC.class, IBirkirkaraFC.class, INorthamptonTownFC.class,
		IEnuguRangers.class, IPanamaNationalFootballTeam.class, ISportingClubeDeGoa.class,
		IItalyNationalFootballTeam.class, IPlymouthArgyleFC.class, IBurtonTownFC.class, ITianjinTedaFC.class,
		IUnitedSC.class, IChileNationalFootballTeam.class, INottsCountyFC.class, IJeonnamDragons.class,
		IGatesheadFC.class, ISherwoodForesters.class, })

@ImplementationClass(get = Team.class)
public interface ITeam extends ISoccerPlayerThing {

}
